# Generated by Django 4.2.13 on 2024-06-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=85, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=60, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='user',
            name='tag_user',
            field=models.CharField(max_length=20, null=True, verbose_name='Тег'),
        ),
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.TextField(blank=True, max_length=50, verbose_name='О пользователе'),
        ),
    ]
