# Generated by Django 4.2.13 on 2024-06-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_user_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tag_user',
            field=models.CharField(max_length=20, unique=True, verbose_name='Тег'),
        ),
    ]
