# Generated by Django 4.2.13 on 2024-06-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_alter_user_telephone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telephone_number',
            field=models.CharField(max_length=18, verbose_name='Номер телефона'),
        ),
    ]
